FROM node:alpine As development

WORKDIR /usr/src/app

COPY . .

COPY package*.json ./

RUN yarn install

RUN yarn build gateway

FROM node:alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY tsconfig.app.json ./
COPY ../package*.json ./

RUN yarn install -prod
COPY . .

COPY --from=development /usr/src/app/dist ./dist

# 
CMD ["node", "dist/apps/gateway/main"]