export const JobInterests = [
  "Software Engineer",
  "Full Stack Engineer",
  "Backend Engineer",
  "Frontend Engineer",
  "DevOps Engineer",
  "Data Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "QA Engineer",
  "Mobile Engineer",
  "Security Engineer",
  "Product Manager",
  "Project Manager",
  "Technical Program Manager",
  "UX Designer",
  "UI Designer",
  "UI/UX Designer",
  "Recruiter",
  "Other",
] as const;
