export const Titles = [
  "Backend Engineer",
  "Cloud Architect",
  "Cloud Engineer",
  "Cybersecurity Engineer",
  "Data Analyst",
  "Data Engineer",
  "Data Scientist",
  "Database Administrator",
  "DevOps Engineer",
  "Embedded Systems Engineer",
  "Frontend Engineer",
  "Full Stack Engineer",
  "IT Manager",
  "Machine Learning Engineer",
  "Mobile App Developer",
  "Network Engineer",
  "Other",
  "Product Manager",
  "QA Engineer",
  "Site Reliability Engineer",
  "Software Architect",
  "Software Engineer",
  "Systems Administrator",
  "Systems Analyst",
  "UI/UX Designer",
  "Web Developer",
  "title",
] as const;

export type Title = (typeof Titles)[number];
