import Hamburger from "@/components/utilities/hamburger";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import {
  ArrowTopRightOnSquareIcon,
  ClipboardDocumentIcon,
  GlobeAsiaAustraliaIcon,
} from "@heroicons/react/24/outline";

const MenuItems = ["About", "Features", "Contact"] as const;

export default function Home() {
  const [swap, setSwap] = useState(false);

  return (
    <>
      <Head>
        <title>Swift Hire</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative mx-8 flex flex-col items-center justify-center space-y-16 py-8">
        <div
          className={`fixed ${
            swap ? "top-2" : "top-0"
          } z-50 flex w-full flex-row items-center bg-white py-8 shadow-md shadow-indigo-200`}
        >
          <Image
            src="/logo.png"
            alt=""
            width={148}
            height={148}
            className="ml-8 mr-auto"
          />
          <Hamburger swap={swap} setSwap={() => setSwap((prev) => !prev)} />
          <div
            className={`absolute -top-2 z-10 flex w-full flex-col justify-center bg-indigo-600 pt-24 shadow-2xl duration-500 ${
              swap ? `` : "-translate-y-full shadow-none"
            }`}
          >
            <ul className="flex flex-col">
              {MenuItems.map((item) => (
                <li
                  key={item}
                  className="items-center border-b-2 border-t-2 border-b-transparent px-4 py-2 text-lg font-bold tracking-[3px] text-indigo-200 duration-300 hover:cursor-pointer hover:text-white/95"
                >
                  {item}
                </li>
              ))}
            </ul>
          </div>
        </div>

        <section className="flex w-full flex-col space-y-8 border pb-8 pt-2">
          <h1 className="py-2 text-center text-4xl uppercase tracking-widest">
            About
          </h1>
          <div className="mx-8 flex flex-col space-y-4 leading-8">
            <p className="indent-4 text-lg leading-8 first-letter:text-2xl first-letter:tracking-wide">
              At Swift Hire, we believe that every tech professional deserves a
              seamless process path towards their dream job. We understand the
              unique challenges that individuals in the tech industry face when
              it comes to job hunting, and that's why we've designed a
              revolutionary application that empowers you to secure your ideal
              tech role swiftly and effortlessly.
            </p>
            <p className="indent-4 text-lg leading-8 first-letter:text-2xl first-letter:tracking-wide">
              Our mission is to bridge the gap between exceptional tech talent
              and the perfect job opportunities. We're committed to transforming
              the way tech professionals navigate their careers by providing
              them with a cutting-edge platform tailored to their unique needs.
              Swift Hire is more than just an application; it's a transformative
              tool that simplifies the job search process, making it quicker,
              smarter, and more rewarding when you land that job.
            </p>
          </div>
          <div className="flex flex-row items-center justify-evenly">
            <button className="rounded-md border-indigo-400 bg-indigo-400 px-5 py-2 tracking-wider">
              Contact Us
            </button>
            <button className="flex flex-row items-center space-x-1 px-1 py-0.5">
              <p className="text-lg font-bold text-indigo-400 underline decoration-2 underline-offset-2">
                Try it out!
              </p>
              <ArrowTopRightOnSquareIcon className="h-5 w-5 text-indigo-400" />
            </button>
          </div>
        </section>

        <section className="flex w-full flex-col space-y-8 border pb-8 pt-2">
          <h1 className="py-2 text-center text-4xl uppercase tracking-widest">
            Features
          </h1>

          <div className="mx-8 flex flex-col space-y-4 rounded-lg border-2 px-6 py-8">
            <span className="flex flex-row items-center space-x-1 text-xl">
              <h2>Discovery Graph</h2>
              <GlobeAsiaAustraliaIcon className="h-6 w-6" />
            </span>

            <p>
              Elevate your visibility designed to showcase your skills and
              features. The discovery graph is a{" "}
              <span className="font-bold tracking-wide text-indigo-400 underline decoration-2 underline-offset-2">
                powerful
              </span>{" "}
              tool for recruiters to see what kind of talent is out in the wild.
              Its a place to showcase your skills and to see if you could be
              their{" "}
              <span className="font-bold tracking-wide text-indigo-400 underline decoration-2 underline-offset-2">
                next
              </span>{" "}
              hire.
            </p>
          </div>
          <div className="mx-8 flex flex-col space-y-4 rounded-lg border-2 px-6 py-8">
            <span className="flex flex-row items-center space-x-1 text-xl">
              <h2>Boosted Applications</h2>
              <ClipboardDocumentIcon className="h-6 w-6" />
            </span>

            <p>
              Show some enthusiasm the company you are applying to that you are{" "}
              <span className="font-bold tracking-wide text-indigo-400 underline decoration-2 underline-offset-2">
                serious
              </span>{" "}
              about the position. Boosted Applications are a great way to{" "}
              <span className="font-bold tracking-wide text-indigo-400 underline decoration-2 underline-offset-2">
                stand out
              </span>{" "}
              from the crowd and telling the company you mean business. This
              dynamic tool communicates to employers that you're not just
              another applicant – you're genuinely interested and passionate
              about the role.
            </p>
          </div>
        </section>
      </main>
      <footer className="relative bg-indigo-400 p-2">
        <div className="flex flex-row justify-evenly">
          <div className="flex flex-col items-center justify-center space-y-2.5">
            <h4 className="text-xs">Company</h4>

            <ul className="flex flex-col">
              <li>Careers</li>
            </ul>
          </div>
        </div>
        <p className="absolute bottom-2 text-sm text-white">
          © 2021 Swift Hire
        </p>
      </footer>
    </>
  );
}
