version: "3.8"

services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/dockerfile
      target: development
    command: yarn start:dev gateway
    environment:
      - NODE_ENV=docker
    env_file:
      - ./apps/gateway/.env.local.docker
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - swift_hire
    ports:
      - 8080:8080
<<<<<<< HEAD
=======

>>>>>>> api-main
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/dockerfile
      target: development
    command: yarn start:dev auth
    environment:
      - NODE_ENV=docker
    env_file:
      - ./apps/auth/.env.local.docker
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - swift_hire
<<<<<<< HEAD
    ports:
      - 8081
=======

  users:
    build:
      context: .
      dockerfile: ./apps/users/dockerfile
      target: development
    command: yarn start:dev users
    environment:
      - NODE_ENV=docker
    env_file:
      - ./apps/users/.env.local.docker
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - swift_hire
>>>>>>> api-main

networks:
  swift_hire:
    external: false
