version: "3.8"

services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/dockerfile
      target: development
    command: yarn start:dev gateway
    environment:
      - NODE_ENV=docker
    env_file:
      - ./apps/gateway/.env.local.docker
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - swift_hire
    ports:
      - 8080:8080

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/dockerfile
      target: development
    command: yarn start:dev auth
    environment:
      - NODE_ENV=docker
    env_file:
      - ./apps/auth/.env.local.docker
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - swift_hire

  users:
    build:
      context: .
      dockerfile: ./apps/users/dockerfile
      target: development
    command: yarn start:dev users
    environment:
      - NODE_ENV=docker
    env_file:
      - ./apps/users/.env.local.docker
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - swift_hire

  jobs:
    build:
      context: .
      dockerfile: ./apps/jobs/dockerfile
      target: development
    command: yarn start:dev jobs
    environment:
      - NODE_ENV=docker
    env_file:
      - ./apps/jobs/.env.local.docker
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - swift_hire

networks:
  swift_hire:
    external: false
