export const JobInterestsList = [
  { label: "Software Engineer", value: "Software Engineer" },
  { label: "Full Stack Engineer", value: "Full Stack Engineer" },
  { label: "Backend Engineer", value: "Backend Engineer" },
  { label: "Frontend Engineer", value: "Frontend Engineer" },
  { label: "DevOps Engineer", value: "DevOps Engineer" },
  { label: "Data Engineer", value: "Data Engineer" },
  { label: "Data Scientist", value: "Data Scientist" },
  { label: "Machine Learning Engineer", value: "Machine Learning Engineer" },
  { label: "QA Engineer", value: "QA Engineer" },
  { label: "Mobile Engineer", value: "Mobile Engineer" },
  { label: "Security Engineer", value: "Security Engineer" },
  { label: "Product Manager", value: "Product Manager" },
  { label: "Project Manager", value: "Project Manager" },
  { label: "Technical Program Manager", value: "Technical Program Manager" },
  { label: "UX Designer", value: "UX Designer" },
  { label: "UI Designer", value: "UI Designer" },
  { label: "UI/UX Designer", value: "UI/UX Designer" },
  { label: "Recruiter", value: "Recruiter" },
  { label: "Other", value: "Other" },
];

export const JobInterests = [
  "Software Engineer",
  "Full Stack Engineer",
  "Backend Engineer",
  "Frontend Engineer",
  "DevOps Engineer",
  "Data Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "QA Engineer",
  "Mobile Engineer",
  "Security Engineer",
  "Product Manager",
  "Project Manager",
  "Technical Program Manager",
  "UX Designer",
  "UI Designer",
  "UI/UX Designer",
  "Recruiter",
  "Other",
] as const;

export type JobInterest = (typeof JobInterests)[number];
