export const SkillList = [
  { label: "JavaScript", value: "JavaScript" },
  { label: "TypeScript", value: "TypeScript" },
  { label: "NestJs", value: "NestJs" },
  { label: "TailwindCss", value: "TailwindCss" },
  { label: "Material UI", value: "Material UI" },
  { label: "Sass", value: "Sass" },
  { label: "Bootstrap", value: "Bootstrap" },
  { label: "Chakra UI", value: "Chakra UI" },
  { label: "Less", value: "Less" },
  { label: "NextJs", value: "NextJs" },
  { label: "ReactJs", value: "ReactJs" },
  { label: "PostgreSQL", value: "PostgreSQL" },
  { label: "MySQL", value: "MySQL" },
  { label: "Sqlite", value: "Sqlite" },
  { label: "MongoDB", value: "MongoDB" },
  { label: "Redis", value: "Redis" },
  { label: "Firebase", value: "Firebase" },
  { label: "Supabase", value: "Supabase" },
  { label: "GraphQL", value: "GraphQL" },
  { label: "Apollo", value: "Apollo" },
  { label: "Hasura", value: "Hasura" },
  { label: "CockroachDB", value: "CockroachDB" },
  { label: "FaunaDB", value: "FaunaDB" },
  { label: "ScyllaDB", value: "ScyllaDB" },
  { label: "React Native", value: "React Native" },
  { label: "VueJs", value: "VueJs" },
  { label: "Angular", value: "Angular" },
  { label: "Angular 2", value: "Angular 2" },
  { label: "Qwik", value: "Qwik" },
  { label: "Svelte", value: "Svelte" },
  { label: "Svelte Kit", value: "Svelte Kit" },
  { label: "NuxtJs", value: "NuxtJs" },
  { label: "Express", value: "Express" },
  { label: "Remix Js", value: "Remix Js" },
  { label: "Deno", value: "Deno" },
  { label: "Other", value: "Other" },
  { label: "Solid Js", value: "Solid Js" },
  { label: "Solid start", value: "Solid start" },
  { label: "NodeJs", value: "NodeJs" },
  { label: "AWS", value: "AWS" },
  { label: "Azure", value: "Azure" },
  { label: "Google Cloud", value: "Google Cloud" },
  { label: "Heroku", value: "Heroku" },
  { label: "Vercel", value: "Vercel" },
  { label: "Netlify", value: "Netlify" },
  { label: "Digital Ocean", value: "Digital Ocean" },
  { label: "Linode", value: "Linode" },
  { label: "Cloudflare", value: "Cloudflare" },
  { label: "Cloudinary", value: "Cloudinary" },
  { label: "Fastly", value: "Fastly" },
  { label: "C", value: "C" },
  { label: "C++", value: "C++" },
  { label: "C#", value: "C#" },
  { label: "ASP .Net", value: "ASP .Net" },
  { label: "Entity Framework", value: "Entity Framework" },
  { label: "Springboot", value: "Springboot" },
  { label: "Maven", value: "Maven" },
  { label: "Gradle", value: "Gradle" },
  { label: "Java", value: "Java" },
  { label: "Python", value: "Python" },
  { label: "Django", value: "Django" },
  { label: "Flask", value: "Flask" },
  { label: "FastAPI", value: "FastAPI" },
  { label: "Ruby on Rails", value: "Ruby on Rails" },
  { label: "Laravel", value: "Laravel" },
  { label: "Ruby", value: "Ruby" },
  { label: "PHP", value: "PHP" },
  { label: "SQL", value: "SQL" },
  { label: "HTML", value: "HTML" },
  { label: "CSS", value: "CSS" },
  { label: "Swift", value: "Swift" },
  { label: "Swift UI", value: "Swift UI" },
  { label: "Kotlin", value: "Kotlin" },
  { label: "Go", value: "Go" },
  { label: "Rust", value: "Rust" },
  { label: "Scala", value: "Scala" },
  { label: "Perl", value: "Perl" },
  { label: "Haskell", value: "Haskell" },
  { label: "Lua", value: "Lua" },
  { label: "R", value: "R" },
  { label: "Matlab", value: "Matlab" },
  { label: "Assembly", value: "Assembly" },
  { label: "Objective-C", value: "Objective-C" },
  { label: "Visual Basic", value: "Visual Basic" },
  { label: "Dart", value: "Dart" },
  { label: "Elixir", value: "Elixir" },
  { label: "Clojure", value: "Clojure" },
  { label: "Groovy", value: "Groovy" },
  { label: "Julia", value: "Julia" },
  { label: "F#", value: "F#" },
  { label: "Erlang", value: "Erlang" },
  { label: "Bash", value: "Bash" },
  { label: "PowerShell", value: "PowerShell" },
  { label: "OCaml", value: "OCaml" },
  { label: "Scheme", value: "Scheme" },
  { label: "VimL", value: "VimL" },
  { label: "Apex", value: "Apex" },
  { label: "Arduino", value: "Arduino" },
  { label: "Crystal", value: "Crystal" },
  { label: "D", value: "D" },
  { label: "Docker", value: "Docker" },
  { label: "Kubernetes", value: "Kubernetes" },
  { label: "Helm", value: "Helm" },
  { label: "Git", value: "Git" },
  { label: "Jira", value: "Jira" },
  { label: "Trello", value: "Trello" },
  { label: "Nim", value: "Nim" },
  { label: "Pascal", value: "Pascal" },
].sort((a, b) => (a.label < b.label ? -1 : 1));

const skills = [
  "JavaScript",
  "TypeScript",
  "NestJs",
  "TailwindCss",
  "Material UI",
  "Sass",
  "Bootstrap",
  "Chakra UI",
  "Less",
  "NextJs",
  "ReactJs",
  "PostgreSQL",
  "MySQL",
  "Sqlite",
  "MongoDB",
  "Redis",
  "Firebase",
  "Supabase",
  "GraphQL",
  "Apollo",
  "Hasura",
  "CockroachDB",
  "FaunaDB",
  "ScyllaDB",
  "React Native",
  "VueJs",
  "Angular",
  "Angular 2",
  "Qwik",
  "Svelte",
  "Svelte Kit",
  "NuxtJs",
  "Express",
  "Remix Js",
  "Deno",
  "Other",
  "solid Js",
  "solid start",
  "NodeJs",
  "AWS",
  "Azure",
  "Google Cloud",
  "Heroku",
  "Vercel",
  "Netlify",
  "Digital Ocean",
  "Linode",
  "Cloudflare",
  "Cloudinary",
  "Fastly",
  "C",
  "C++",
  "C#",
  "ASP .Net",
  "Entity Framework",
  "Springboot",
  "Maven",
  "Gradle",
  "Java",
  "Python",
  "Django",
  "Flask",
  "FastAPI",
  "Ruby on Rails",
  "Laravel",
  "Ruby",
  "PHP",
  "SQL",
  "HTML",
  "CSS",
  "Swift",
  "Swift UI",
  "Kotlin",
  "Go",
  "Rust",
  "Scala",
  "Perl",
  "Haskell",
  "Lua",
  "R",
  "Matlab",
  "Assembly",
  "Objective-C",
  "Visual Basic",
  "Dart",
  "Elixir",
  "Clojure",
  "Groovy",
  "Julia",
  "F#",
  "Erlang",
  "Bash",
  "PowerShell",
  "OCaml",
  "Scheme",
  "VimL",
  "Apex",
  "Arduino",
  "Crystal",
  "D",
  "Docker",
  "Kubernetes",
  "Helm",
  "Git",
  "Jira",
  "Trello",
  "Nim",
  "Pascal",
] as const;

export type SkillName = (typeof skills)[number];
export type Skill = { name: (typeof skills)[number]; otherName?: string };
