export const Titles = [
  { label: "Backend Engineer", value: "Backend Engineer" },
  { label: "Cloud Architect", value: "Cloud Architect" },
  { label: "Cloud Engineer", value: "Cloud Engineer" },
  { label: "Cybersecurity Engineer", value: "Cybersecurity Engineer" },
  { label: "Data Analyst", value: "Data Analyst" },
  { label: "Data Engineer", value: "Data Engineer" },
  { label: "Data Scientist", value: "Data Scientist" },
  { label: "Database Administrator", value: "Database Administrator" },
  { label: "DevOps Engineer", value: "DevOps Engineer" },
  { label: "Embedded Systems Engineer", value: "Embedded Systems Engineer" },
  { label: "Frontend Engineer", value: "Frontend Engineer" },
  { label: "Full Stack Engineer", value: "Full Stack Engineer" },
  { label: "IT Manager", value: "IT Manager" },
  { label: "Machine Learning Engineer", value: "Machine Learning Engineer" },
  { label: "Mobile App Developer", value: "Mobile App Developer" },
  { label: "Network Engineer", value: "Network Engineer" },
  { label: "Other", value: "Other" },
  { label: "Product Manager", value: "Product Manager" },
  { label: "QA Engineer", value: "QA Engineer" },
  { label: "Site Reliability Engineer", value: "Site Reliability Engineer" },
  { label: "Software Architect", value: "Software Architect" },
  { label: "Software Engineer", value: "Software Engineer" },
  { label: "Systems Administrator", value: "Systems Administrator" },
  { label: "Systems Analyst", value: "Systems Analyst" },
  { label: "UI/UX Designer", value: "UI/UX Designer" },
  { label: "Web Developer", value: "Web Developer" },
];

export type Title = (typeof Titles)[number];
